---
- hosts: all
  become: true
  vars_files:
    - "../{{ host }}/vars.yml"

  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
      loop: [ 'zip', 'unzip' ]

    - unarchive:
        src: /tmp/cert.zip
        dest: /

    # equivalent to: 0 6 * * 1
    - cron:
        name: "Renew certificate"
        minute: "0"
        hour: "6"
        weekday: "1"
        job: "sh {{ directory }}/bin/renew 2>&1 | /usr/bin/logger -t letsencrypt"
