---
- hosts: all
  become: true
  vars_files:
    - "../{{ host }}/vars.yml"

  tasks:
    - name: Copy certificate respecting symlinks
      ansible.posix.synchronize:
        src: /tmp/cert
        dest: /

    # equivalent to: 0 6 * * 1
    - cron:
        name: "Renew certificate"
        minute: "0"
        hour: "6"
        weekday: "1"
        job: "sh {{ directory }}/bin/renew 2>&1 | /usr/bin/logger -t letsencrypt"
