---
- hosts: all
  become: true
  vars_files:
    - "../{{ host }}/vars.yml"

  tasks:
    - git:
        repo: "{{ repository }}"
        dest: "{{ directory }}"

    - copy:
        src: ~/Dropbox/erza/.env
        dest: "{{ directory }}/{{ host }}"
        mode: 644
