---
- hosts: all
  become: true
  vars_files:
    - "../{{ host }}/vars.yml"

  tasks:
    - file:
        path: /root/.ssh
        owner: root
        state: directory
        mode: '700'

    - name: Enable SSH Access
      copy:
        src: ~/.ssh/id_ed25519.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '600'
