---
- hosts: all
  become: true
  vars_files:
    - "../{{ host }}/vars.yml"

  tasks:
    - user:
        name: "{{ user }}"
        shell: /bin/bash
        groups: docker
        append: yes
        system: true

    - file:
        path: /home/{{ user }}/.ssh
        owner: "{{ user }}"
        state: directory
        mode: '700'

    - copy:
        src: /tmp/authorized_keys
        dest: /home/{{ user }}/.ssh/authorized_keys
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '600'

    - file:
        path: /root/.ssh
        owner: root
        state: directory
        mode: '700'

    - name: Enable SSH Access
      copy:
        src: ~/.ssh/id_ed25519.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '600'
